import type { Metadata } from "next";
import "./globals.css";

// Plain system-font stacks instead of next/font/google: that package fetches
// the font files from Google Fonts at build time, so the build hard-fails
// whenever the build machine has no outbound internet access to Google.
const fontVariableStyle = {
  "--font-geist-sans":
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  "--font-geist-mono":
    "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
} as React.CSSProperties;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" style={fontVariableStyle}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
