/** Canonical skill catalog seeded into the `skills` table when missing. */
export type DefaultSkill = { skill_name: string; category: string };

export const DEFAULT_SKILLS: DefaultSkill[] = [
  // Technology
  { skill_name: "Python Programming", category: "Technology" },
  { skill_name: "JavaScript", category: "Technology" },
  { skill_name: "TypeScript", category: "Technology" },
  { skill_name: "React", category: "Technology" },
  { skill_name: "Next.js", category: "Technology" },
  { skill_name: "Node.js", category: "Technology" },
  { skill_name: "Java", category: "Technology" },
  { skill_name: "C++", category: "Technology" },
  { skill_name: "Go", category: "Technology" },
  { skill_name: "Swift", category: "Technology" },
  { skill_name: "Kotlin", category: "Technology" },
  { skill_name: "Flutter", category: "Technology" },
  { skill_name: "React Native", category: "Technology" },
  { skill_name: "SQL & Databases", category: "Technology" },
  { skill_name: "Data Science", category: "Technology" },
  { skill_name: "Machine Learning", category: "Technology" },
  { skill_name: "Cybersecurity", category: "Technology" },
  { skill_name: "DevOps & Cloud", category: "Technology" },
  { skill_name: "AWS", category: "Technology" },
  { skill_name: "Docker", category: "Technology" },
  { skill_name: "Git & GitHub", category: "Technology" },
  { skill_name: "Web Development", category: "Technology" },
  { skill_name: "Mobile Development", category: "Technology" },
  { skill_name: "Excel", category: "Technology" },
  { skill_name: "Power BI", category: "Technology" },
  { skill_name: "Tableau", category: "Technology" },

  // Design
  { skill_name: "UI/UX Design", category: "Design" },
  { skill_name: "Figma", category: "Design" },
  { skill_name: "Graphic Design", category: "Design" },
  { skill_name: "Video Editing", category: "Design" },
  { skill_name: "Motion Design", category: "Design" },
  { skill_name: "Illustration", category: "Design" },
  { skill_name: "Product Design", category: "Design" },
  { skill_name: "Typography", category: "Design" },
  { skill_name: "3D Modeling", category: "Design" },
  { skill_name: "Adobe Photoshop", category: "Design" },
  { skill_name: "Adobe Illustrator", category: "Design" },
  { skill_name: "Canva", category: "Design" },

  // Art
  { skill_name: "Painting", category: "Art" },
  { skill_name: "Drawing", category: "Art" },
  { skill_name: "Digital Art", category: "Art" },
  { skill_name: "Sculpture", category: "Art" },
  { skill_name: "Calligraphy", category: "Art" },
  { skill_name: "Photography", category: "Art" },
  { skill_name: "Art History", category: "Art" },
  { skill_name: "Crafts & DIY", category: "Art" },

  // Business
  { skill_name: "Public Speaking", category: "Business" },
  { skill_name: "Entrepreneurship", category: "Business" },
  { skill_name: "Project Management", category: "Business" },
  { skill_name: "Product Management", category: "Business" },
  { skill_name: "Accounting", category: "Business" },
  { skill_name: "Finance Basics", category: "Business" },
  { skill_name: "Negotiation", category: "Business" },
  { skill_name: "Leadership", category: "Business" },
  { skill_name: "Sales", category: "Business" },
  { skill_name: "Business Strategy", category: "Business" },

  // Marketing
  { skill_name: "Digital Marketing", category: "Marketing" },
  { skill_name: "Content Marketing", category: "Marketing" },
  { skill_name: "SEO", category: "Marketing" },
  { skill_name: "Social Media Marketing", category: "Marketing" },
  { skill_name: "Copywriting", category: "Marketing" },
  { skill_name: "Brand Strategy", category: "Marketing" },
  { skill_name: "Email Marketing", category: "Marketing" },
  { skill_name: "Growth Marketing", category: "Marketing" },

  // Soft Skills
  { skill_name: "Communication", category: "Soft Skills" },
  { skill_name: "Time Management", category: "Soft Skills" },
  { skill_name: "Critical Thinking", category: "Soft Skills" },
  { skill_name: "Teamwork", category: "Soft Skills" },
  { skill_name: "Mentoring", category: "Soft Skills" },
  { skill_name: "Interview Prep", category: "Soft Skills" },
  { skill_name: "Career Coaching", category: "Soft Skills" },
  { skill_name: "Conflict Resolution", category: "Soft Skills" },

  // Languages
  { skill_name: "English", category: "Languages" },
  { skill_name: "Mandarin Chinese", category: "Languages" },
  { skill_name: "Spanish", category: "Languages" },
  { skill_name: "French", category: "Languages" },
  { skill_name: "Japanese", category: "Languages" },
  { skill_name: "Korean", category: "Languages" },
  { skill_name: "Indonesian", category: "Languages" },
  { skill_name: "German", category: "Languages" },
  { skill_name: "Arabic", category: "Languages" },
  { skill_name: "Translation", category: "Languages" },

  // Music
  { skill_name: "Guitar", category: "Music" },
  { skill_name: "Piano", category: "Music" },
  { skill_name: "Singing", category: "Music" },
  { skill_name: "Music Theory", category: "Music" },
  { skill_name: "Drumming", category: "Music" },
  { skill_name: "Violin", category: "Music" },
  { skill_name: "Music Production", category: "Music" },
  { skill_name: "DJ Mixing", category: "Music" },
  { skill_name: "Ukulele", category: "Music" },

  // Fitness & Wellness
  { skill_name: "Yoga", category: "Fitness" },
  { skill_name: "Strength Training", category: "Fitness" },
  { skill_name: "Running", category: "Fitness" },
  { skill_name: "Swimming", category: "Fitness" },
  { skill_name: "Martial Arts", category: "Fitness" },
  { skill_name: "Meditation", category: "Fitness" },
  { skill_name: "Nutrition", category: "Fitness" },
  { skill_name: "Dance", category: "Fitness" },
  { skill_name: "Pilates", category: "Fitness" },

  // Food & Lifestyle
  { skill_name: "Cooking", category: "Food & Lifestyle" },
  { skill_name: "Baking", category: "Food & Lifestyle" },
  { skill_name: "Coffee Brewing", category: "Food & Lifestyle" },
  { skill_name: "Gardening", category: "Food & Lifestyle" },
  { skill_name: "Fashion Styling", category: "Food & Lifestyle" },
  { skill_name: "Interior Design", category: "Food & Lifestyle" },
  { skill_name: "Travel Planning", category: "Food & Lifestyle" },

  // Education & Writing
  { skill_name: "Tutoring", category: "Education" },
  { skill_name: "Math Tutoring", category: "Education" },
  { skill_name: "Science Tutoring", category: "Education" },
  { skill_name: "Essay Writing", category: "Education" },
  { skill_name: "Creative Writing", category: "Education" },
  { skill_name: "Technical Writing", category: "Education" },
  { skill_name: "Study Skills", category: "Education" },
  { skill_name: "Research Methods", category: "Education" },

  // Games & Media
  { skill_name: "Game Design", category: "Games & Media" },
  { skill_name: "Streaming", category: "Games & Media" },
  { skill_name: "Podcasting", category: "Games & Media" },
  { skill_name: "YouTube Creation", category: "Games & Media" },
  { skill_name: "Chess", category: "Games & Media" },
  { skill_name: "Esports Coaching", category: "Games & Media" },
];
